name: Update Site Data

on:
  workflow_dispatch:
  workflow_call:

jobs:
  generate_data:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Update data
        run: yarn run update-site-data
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: Update site data'
          file_pattern: static/data/**
