name: Deploy Site

on:
  workflow_run:
    workflows: ['Release']
    branches: [main]
    types: 
      - completed

jobs:
  deploy-site:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ifood/.workflows/.github/workflows/site_publish.yml@main
    with:
      directory: .
